image: ruby:3.2-bullseye

stages:
  - build
  - deploy
  - mirror
  - sync

variables:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  PAGES_DIR: public
  GIT_DEPTH: 0  # Full clone for build, but not used for GitHub mirroring

build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y nodejs
    - gem install bundler
    - bundle install
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - bundle exec jekyll build -d $PAGES_DIR
  artifacts:
    paths:
      - $PAGES_DIR

pages:
  stage: deploy
  before_script: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - $PAGES_DIR
  after_script:
  - echo "Notifying contributor via GitHub..."
  - |
    # Look through the last 10 commits on main to find one associated with a GitHub PR
    COMMIT_SHA=""
    PR_JSON=""
    for sha in $(git log --pretty=format:'%H' -n 10); do
      echo "Checking commit $sha for GitHub PR association..."
      response=$(curl -s \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.groot-preview+json" \
        https://api.github.com/repos/${GITHUB_USER}/gl-copy-site/commits/$sha/pulls)

      if echo "$response" | grep -q '"number":'; then
        COMMIT_SHA=$sha
        PR_JSON=$response
        break
      fi
    done

    if [ -n "$COMMIT_SHA" ]; then
      echo "Found PR-associated commit: $COMMIT_SHA"

      PR_NUMBER=$(echo "$PR_JSON" | grep '"number":' | head -n1 | grep -o '[0-9]\+')
      if [ -n "$PR_NUMBER" ]; then
        echo "Posting deployment comment to PR #$PR_NUMBER"
        curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_USER}/gl-copy-site/issues/${PR_NUMBER}/comments \
          -d "{\"body\": \"Your changes are now live on [GitLab Pages](https://smarvin.gitlab.io/new-site/index.html)\"}"
      else
        echo "PR JSON received, but PR number could not be parsed."
      fi
    else
      echo "No recent commits in main are associated with a GitHub PR. Skipping notification."
    fi

mirror_to_github:
  # Only mirror GitLab's `current` branch to GitHub when a real user pushes or merges.
  # Prevents automatic mirroring after a GitHub-triggered sync (which pushes as "GitLab CI").
  stage: mirror
  rules:
    - if: '$CI_COMMIT_BRANCH == "current" && $CI_PIPELINE_SOURCE == "push" && $GITLAB_USER_LOGIN && $GITLAB_USER_LOGIN !~ /bot_/'
  script:
    - echo "CI_COMMIT_BRANCH is $CI_COMMIT_BRANCH"
    - echo "CI_PIPELINE_SOURCE is $CI_PIPELINE_SOURCE"
    - echo "GITLAB_USER_LOGIN is $GITLAB_USER_LOGIN"
    - echo "Triggered by ${CI_PROJECT_URL}/-/pipelines/${CI_PIPELINE_ID}"
    - echo "Mirroring the Git repo (source code) to GitHub..."
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@example.com"
    - export GITHUB_REPO="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/gl-copy-site.git"
    - git remote add github "$GITHUB_REPO"
    - git remote -v
    - git push --force github HEAD:refs/heads/mirror

sync_github_to_gitlab:
  stage: sync
  image: alpine:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_BRANCH == "current"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "current"'
      when: manual
    - when: never
  before_script:
    - apk add --no-cache git
  script:
    - echo "Syncing GitHub mirror -> GitLab current..."
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@example.com"
    - git clone --branch mirror https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/gl-copy-site.git /tmp/github-mirror
    - cd /tmp/github-mirror
    - git log -1 --oneline  # Optional: verify the commit pulled
    - git remote add gitlab https://oauth2:${PROJECT_ACCESS_TOKEN}@gitlab.com/smarvin/new-site.git
    - git push gitlab mirror:current
